// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package car

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsCarNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserServiceErrorReason_CAR_NOT_FOUND.String() && e.Code == 500
}

func ErrorCarNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, UserServiceErrorReason_CAR_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}
